version: 2.1

orbs:
  maven: circleci/maven@1.1
  heroku: circleci/heroku@1.2.6

workflows:
  test-and-deploy:
    jobs:
      - maven/test
      - heroku/push-docker-image:
          pre-steps:
            - setup_remote_docker:
                version: 19.03.13
          requires:
            - maven/test
          filters:
            branches:
              only: main
