CREATE TABLE USER(
    ID UUID DEFAULT random_uuid() PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    SECOND_NAME VARCHAR(255)
);

INSERT INTO USER(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, SECOND_NAME) VALUES
('NoobMaster69', '1234', 'Bob', 'Dylan', 'Clarence'),
('Thor', 'Jane420', 'Thor', 'Odinsson', NULL);
